# Generated by Django 5.0.2 on 2025-08-06 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_alter_session_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='scheduler.event'),
        ),
    ]
